version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers-legacy
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: NPM Install
          command:
            echo 'npm installing'
            npm install
            CI=true npm run build
  test:
    docker:
      - image: circleci/node:12-browsers-legacy
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Testing
          command:
            echo 'Testing in progress'
            npm test
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - test  




